# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170112_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='datumGereed',
            field=models.DateField(blank=True, null=True, verbose_name='Datum gereed'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.CaseStatus'),
        ),
    ]
