# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20170112_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name_plural': 'Activiteit typen'},
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='id',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='activiteiten',
            name='datumUitgevoerd',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='activiteiten',
            name='uitvoerende',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
